package View;

import java.awt.Toolkit;
import java.io.File;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author debf
 */
public class CompilerJForm extends javax.swing.JFrame {

    /**
     * Creates new form CompilerJForm
     */
    public CompilerJForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerJPanel = new javax.swing.JPanel();
        textEditorJPanel = new javax.swing.JPanel();
        textEditorTittleJpanel = new javax.swing.JPanel();
        titleJLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textEditorJTextArea = new javax.swing.JTextArea();
        logsJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultJTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openJMenuItem = new javax.swing.JMenuItem();
        saveJMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        runJMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        loadExampleJMenuItem = new javax.swing.JMenuItem();
        infoJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        containerJPanel.setLayout(new javax.swing.BoxLayout(containerJPanel, javax.swing.BoxLayout.X_AXIS));

        titleJLabel.setText("EDITOR DE TEXTO");
        textEditorTittleJpanel.add(titleJLabel);

        jPanel2.setLayout(new java.awt.CardLayout());

        textEditorJTextArea.setColumns(20);
        textEditorJTextArea.setRows(5);
        jScrollPane1.setViewportView(textEditorJTextArea);

        jPanel2.add(jScrollPane1, "card2");

        javax.swing.GroupLayout textEditorJPanelLayout = new javax.swing.GroupLayout(textEditorJPanel);
        textEditorJPanel.setLayout(textEditorJPanelLayout);
        textEditorJPanelLayout.setHorizontalGroup(
            textEditorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, textEditorJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(textEditorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textEditorTittleJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        textEditorJPanelLayout.setVerticalGroup(
            textEditorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textEditorJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textEditorTittleJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
        );

        containerJPanel.add(textEditorJPanel);

        jLabel1.setText("RESULTADOS");
        jPanel1.add(jLabel1);

        jPanel3.setLayout(new java.awt.CardLayout());

        resultJTextArea.setEditable(false);
        resultJTextArea.setColumns(20);
        resultJTextArea.setRows(5);
        jScrollPane2.setViewportView(resultJTextArea);

        jPanel3.add(jScrollPane2, "card2");

        javax.swing.GroupLayout logsJPanelLayout = new javax.swing.GroupLayout(logsJPanel);
        logsJPanel.setLayout(logsJPanelLayout);
        logsJPanelLayout.setHorizontalGroup(
            logsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        logsJPanelLayout.setVerticalGroup(
            logsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerJPanel.add(logsJPanel);

        jMenu1.setText("Archivo");

        openJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openJMenuItem.setText("Abrir");
        jMenu1.add(openJMenuItem);

        saveJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveJMenuItem.setText("Guardar");
        jMenu1.add(saveJMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Compilador");

        runJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        runJMenuItem.setText("Ejecutar");
        jMenu4.add(runJMenuItem);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Acerca de");

        loadExampleJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        loadExampleJMenuItem.setText("Ejemplo");
        loadExampleJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadExampleJMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(loadExampleJMenuItem);

        infoJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        infoJMenuItem.setText("Info");
        jMenu2.add(infoJMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Updates current text area and automatically fill the data of a file to
     * display data
     *
     * @param evt
     */
    private void loadExampleJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadExampleJMenuItemActionPerformed
        // SEARCH EXMPLE TEXT
    }//GEN-LAST:event_loadExampleJMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerJPanel;
    public javax.swing.JMenuItem infoJMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JMenuItem loadExampleJMenuItem;
    private javax.swing.JPanel logsJPanel;
    public javax.swing.JMenuItem openJMenuItem;
    public javax.swing.JTextArea resultJTextArea;
    public javax.swing.JMenuItem runJMenuItem;
    public javax.swing.JMenuItem saveJMenuItem;
    private javax.swing.JPanel textEditorJPanel;
    public javax.swing.JTextArea textEditorJTextArea;
    private javax.swing.JPanel textEditorTittleJpanel;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables

    public void setup() {
        // configure sizes
        this.setTitle("PROYECTO ALGEBRA LINEAL : 2121323");
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());

        // configure line counter
        JTextPane textPane = new JTextPane();
        JScrollPane scrollPane = new JScrollPane(textPane);
        TextLineNumber tln = new TextLineNumber(textPane);
        scrollPane.setRowHeaderView(tln);
    }

    /**
     * Display a message
     *
     * @param text
     */
    public void displayMessage(String text) {
        // Create a JTextArea to display the message
        JTextArea textArea = new JTextArea(10, 40);
        textArea.setText(text);
        textArea.setWrapStyleWord(true);
        textArea.setLineWrap(true);
        textArea.setEditable(false);
        // Put the text area in a scroll pane
        JScrollPane scrollPane = new JScrollPane(textArea);
        // Display the scroll pane in a dialog
        JOptionPane.showMessageDialog(null, scrollPane, "INFO", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Get file to save
     * @return File selected to save
     */
    public File chooseFilePathToSave() {
        return this.chooseFilePath(false);
    }

    /**
     * Get file to open
     * @return File to open
     */
    public File chooseFilePathToOpen() {
        return this.chooseFilePath(true);
    }

    /**
     * Display a select to get the path to save file + name
     *
     * @return name or null
     */
    private File chooseFilePath(boolean isOpenFile) {
        JFileChooser fileChooser = new JFileChooser();
        // limit files to search
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text files (*.txt)", "txt");
        fileChooser.setFileFilter(filter);
        // action dialog
        int operation = switch (String.valueOf(isOpenFile)) {
            case "true" -> fileChooser.showSaveDialog(null);
            default -> fileChooser.showOpenDialog(null);
        };
        // check if true option or cancelled
        if (operation == JFileChooser.APPROVE_OPTION) return fileChooser.getSelectedFile();
        else return null;
    }

}
