
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID MATRIX NEWLINE NUMBER SOLVEcode_file : matrix_section solve_sectionmatrix_section   : matrix_declaration\n                        | matrix_declaration matrix_sectionmatrix_declaration : MATRIX ID NEWLINE matrix_content matrix_content   : matrix_row NEWLINE\n                        | matrix_row NEWLINE matrix_contentmatrix_row   : NUMBER\n                    | NUMBER matrix_rowsolve_section : SOLVE solve_listsolve_list   : ID \n                    | ID  solve_list'
    
_lr_action_items = {'MATRIX':([0,3,13,16,18,],[4,4,-4,-5,-6,]),'$end':([1,5,9,10,12,],[0,-1,-9,-10,-11,]),'SOLVE':([2,3,7,13,16,18,],[6,-2,-3,-4,-5,-6,]),'ID':([4,6,10,],[8,10,10,]),'NEWLINE':([8,14,15,17,],[11,16,-7,-8,]),'NUMBER':([11,15,16,],[15,15,15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'code_file':([0,],[1,]),'matrix_section':([0,3,],[2,7,]),'matrix_declaration':([0,3,],[3,3,]),'solve_section':([2,],[5,]),'solve_list':([6,10,],[9,12,]),'matrix_content':([11,16,],[13,18,]),'matrix_row':([11,15,16,],[14,17,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> code_file","S'",1,None,None,None),
  ('code_file -> matrix_section solve_section','code_file',2,'p_code_matrix','MatrixParser.py',10),
  ('matrix_section -> matrix_declaration','matrix_section',1,'p_matrix_dec_section','MatrixParser.py',19),
  ('matrix_section -> matrix_declaration matrix_section','matrix_section',2,'p_matrix_dec_section','MatrixParser.py',20),
  ('matrix_declaration -> MATRIX ID NEWLINE matrix_content','matrix_declaration',4,'p_matrix_declaration','MatrixParser.py',28),
  ('matrix_content -> matrix_row NEWLINE','matrix_content',2,'p_matrix_definition','MatrixParser.py',32),
  ('matrix_content -> matrix_row NEWLINE matrix_content','matrix_content',3,'p_matrix_definition','MatrixParser.py',33),
  ('matrix_row -> NUMBER','matrix_row',1,'p_matrix_definition_line','MatrixParser.py',41),
  ('matrix_row -> NUMBER matrix_row','matrix_row',2,'p_matrix_definition_line','MatrixParser.py',42),
  ('solve_section -> SOLVE solve_list','solve_section',2,'p_solve_section','MatrixParser.py',51),
  ('solve_list -> ID','solve_list',1,'p_operation_list','MatrixParser.py',55),
  ('solve_list -> ID solve_list','solve_list',2,'p_operation_list','MatrixParser.py',56),
]
