// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/resources/grammar/MatrixLexer.flex

/**************************************************/
/************** SECTION 1: USER CODE **************/
/**************************************************/

package Model.Compiler;


import java_cup.runtime.*;
import java.util.ArrayList;
// import sym.*; // avoid, same package
import Model.Utils.CustomLogger;

/**************************************************/
/*************** SECTION 2: CONFIGS ***************/
/**************************************************/

@SuppressWarnings("fallthrough")
public class MatrixLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  3,  4,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  0,  5,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10, 11, 12, 13, 
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14,  0, 15,  0,  0,  0,  0, 
     0, 16, 17, 18, 19, 20, 17, 21, 22, 23, 24, 25, 17, 26, 27, 28, 
    29, 17, 30, 31, 32, 33, 34, 17, 35, 36, 17, 37,  0, 38,  0, 39, 
     0, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\11\14\1\15\1\16"+
    "\1\0\1\17\2\0\10\14\1\20\1\12\2\14\1\21"+
    "\2\14\1\22\13\14\1\23\1\24\2\14\1\25\5\14"+
    "\1\26\1\27\1\30\1\31\1\32";

  private static int [] zzUnpackAction() {
    int [] result = new int[70];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\50\0\50\0\50\0\50"+
    "\0\50\0\240\0\310\0\360\0\50\0\u0118\0\u0140\0\u0168"+
    "\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\u0258\0\50\0\50"+
    "\0\170\0\170\0\u0280\0\u02a8\0\u02d0\0\u02f8\0\u0320\0\u0348"+
    "\0\u0370\0\u0398\0\u03c0\0\u03e8\0\50\0\u02a8\0\u0410\0\u0438"+
    "\0\u0140\0\u0460\0\u0488\0\u0140\0\u04b0\0\u04d8\0\u0500\0\u0528"+
    "\0\u0550\0\u0578\0\u05a0\0\u05c8\0\u05f0\0\u0618\0\u0640\0\u0140"+
    "\0\u0140\0\u0668\0\u0690\0\u0140\0\u06b8\0\u06e0\0\u0708\0\u0730"+
    "\0\u0758\0\u0140\0\u0140\0\u0140\0\u0140\0\u0140";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[70];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\2\1\13\1\14\1\15\1\16"+
    "\2\17\1\20\1\21\1\22\1\17\1\23\1\24\1\17"+
    "\1\25\3\17\1\26\6\17\1\27\1\30\1\2\51\0"+
    "\2\3\1\0\1\3\43\0\2\31\3\0\1\32\42\31"+
    "\16\0\1\14\46\0\1\33\46\0\1\34\1\0\1\14"+
    "\47\0\1\17\1\0\16\17\1\35\6\17\2\0\1\17"+
    "\16\0\1\17\1\0\25\17\2\0\1\17\16\0\1\17"+
    "\1\0\4\17\1\36\20\17\2\0\1\17\16\0\1\17"+
    "\1\0\13\17\1\37\11\17\2\0\1\17\16\0\1\17"+
    "\1\0\1\40\24\17\2\0\1\17\16\0\1\17\1\0"+
    "\13\17\1\41\11\17\2\0\1\17\16\0\1\17\1\0"+
    "\14\17\1\42\10\17\2\0\1\17\16\0\1\17\1\0"+
    "\1\43\24\17\2\0\1\17\16\0\1\17\1\0\1\44"+
    "\24\17\2\0\1\17\2\33\1\45\2\0\43\33\16\0"+
    "\1\46\47\0\1\17\1\0\7\17\1\47\15\17\2\0"+
    "\1\17\16\0\1\17\1\0\2\17\1\50\15\17\1\51"+
    "\4\17\2\0\1\17\16\0\1\17\1\0\2\17\1\52"+
    "\22\17\2\0\1\17\16\0\1\17\1\0\21\17\1\53"+
    "\3\17\2\0\1\17\16\0\1\17\1\0\22\17\1\54"+
    "\2\17\2\0\1\17\16\0\1\17\1\0\16\17\1\55"+
    "\6\17\2\0\1\17\16\0\1\17\1\0\16\17\1\56"+
    "\1\17\1\57\4\17\2\0\1\17\16\0\1\17\1\0"+
    "\13\17\1\60\11\17\2\0\1\17\16\0\1\17\1\0"+
    "\20\17\1\61\4\17\2\0\1\17\16\0\1\17\1\0"+
    "\16\17\1\62\6\17\2\0\1\17\16\0\1\17\1\0"+
    "\16\17\1\63\6\17\2\0\1\17\16\0\1\17\1\0"+
    "\17\17\1\64\5\17\2\0\1\17\16\0\1\17\1\0"+
    "\3\17\1\65\21\17\2\0\1\17\16\0\1\17\1\0"+
    "\11\17\1\66\13\17\2\0\1\17\16\0\1\17\1\0"+
    "\16\17\1\67\6\17\2\0\1\17\16\0\1\17\1\0"+
    "\11\17\1\70\13\17\2\0\1\17\16\0\1\17\1\0"+
    "\6\17\1\71\16\17\2\0\1\17\16\0\1\17\1\0"+
    "\24\17\1\72\2\0\1\17\16\0\1\17\1\0\24\17"+
    "\1\73\2\0\1\17\16\0\1\17\1\0\17\17\1\74"+
    "\5\17\2\0\1\17\16\0\1\17\1\0\1\75\24\17"+
    "\2\0\1\17\16\0\1\17\1\0\14\17\1\76\10\17"+
    "\2\0\1\17\16\0\1\17\1\0\7\17\1\77\15\17"+
    "\2\0\1\17\16\0\1\17\1\0\15\17\1\100\7\17"+
    "\2\0\1\17\16\0\1\17\1\0\15\17\1\101\7\17"+
    "\2\0\1\17\16\0\1\17\1\0\13\17\1\102\11\17"+
    "\2\0\1\17\16\0\1\17\1\0\22\17\1\103\2\17"+
    "\2\0\1\17\16\0\1\17\1\0\23\17\1\104\1\17"+
    "\2\0\1\17\16\0\1\17\1\0\20\17\1\105\4\17"+
    "\2\0\1\17\16\0\1\17\1\0\20\17\1\106\4\17"+
    "\2\0\1\17";

  private static int [] zzUnpacktrans() {
    int [] result = new int[1920];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\5\11\3\1\1\11\11\1\2\11"+
    "\1\0\1\1\2\0\10\1\1\11\41\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[70];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // Java code that can be included in the generated lexer

    public void addError(String lexeme) {
        try {
            CustomLogger.getInstance().addLog(String.format("LEXICAL ERROR | Error at line %1$d column %2$d, lexeme %3$s", yyline+1, yycolumn+1, lexeme), true);
        } catch(Exception e) {
            CustomLogger.getInstance().addLog("Unable to save error at lexer class", true);
        }

    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MatrixLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { addError(yytext()); return new Symbol(sym.UNKNOWN, yyline+1, yycolumn+1);
            }
          // fall through
          case 27: break;
          case 2:
            { /*ignore this line*/
            }
          // fall through
          case 28: break;
          case 3:
            { return new Symbol(sym.LPARENTHESIS, yyline+1, yycolumn+1);
            }
          // fall through
          case 29: break;
          case 4:
            { return new Symbol(sym.RPARENTHESIS, yyline+1, yycolumn+1);
            }
          // fall through
          case 30: break;
          case 5:
            { return new Symbol(sym.TIMES, yyline+1, yycolumn+1);
            }
          // fall through
          case 31: break;
          case 6:
            { return new Symbol(sym.PLUS, yyline+1, yycolumn+1);
            }
          // fall through
          case 32: break;
          case 7:
            { return new Symbol(sym.COMMA, yyline+1, yycolumn+1);
            }
          // fall through
          case 33: break;
          case 8:
            { return new Symbol(sym.MINUS, yyline+1, yycolumn+1);
            }
          // fall through
          case 34: break;
          case 9:
            { return new Symbol(sym.DIVIDE, yyline+1, yycolumn+1);
            }
          // fall through
          case 35: break;
          case 10:
            { return new Symbol(sym.NUMBER, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 36: break;
          case 11:
            { return new Symbol(sym.SEMI_COLON, yyline+1, yycolumn+1);
            }
          // fall through
          case 37: break;
          case 12:
            { return new Symbol(sym.IDENTIFIER, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 38: break;
          case 13:
            { return new Symbol(sym.LBRACKET, yyline+1, yycolumn+1);
            }
          // fall through
          case 39: break;
          case 14:
            { return new Symbol(sym.RBRACKET, yyline+1, yycolumn+1);
            }
          // fall through
          case 40: break;
          case 15:
            { return new Symbol(sym.STRING, yyline+1, yycolumn+1);
            }
          // fall through
          case 41: break;
          case 16:
            { /* Ignore */
            }
          // fall through
          case 42: break;
          case 17:
            { return new Symbol(sym.DETERMINANT, yyline+1, yycolumn+1);
            }
          // fall through
          case 43: break;
          case 18:
            { return new Symbol(sym.INVERSE, yyline+1, yycolumn+1);
            }
          // fall through
          case 44: break;
          case 19:
            { return new Symbol(sym.RANK, yyline+1, yycolumn+1);
            }
          // fall through
          case 45: break;
          case 20:
            { return new Symbol(sym.ARITH, yyline+1, yycolumn+1);
            }
          // fall through
          case 46: break;
          case 21:
            { return new Symbol(sym.GAUSS, yyline+1, yycolumn+1);
            }
          // fall through
          case 47: break;
          case 22:
            { return new Symbol(sym.JORDAN, yyline+1, yycolumn+1);
            }
          // fall through
          case 48: break;
          case 23:
            { return new Symbol(sym.MARKOV, yyline+1, yycolumn+1);
            }
          // fall through
          case 49: break;
          case 24:
            { return new Symbol(sym.MATRIX, yyline+1, yycolumn+1);
            }
          // fall through
          case 50: break;
          case 25:
            { return new Symbol(sym.DECRYPT, yyline+1, yycolumn+1);
            }
          // fall through
          case 51: break;
          case 26:
            { return new Symbol(sym.ENCRYPT, yyline+1, yycolumn+1);
            }
          // fall through
          case 52: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
