
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Model.Compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 7;
  public static final int DECRYPT = 18;
  public static final int PLUS = 6;
  public static final int RANK = 16;
  public static final int MARKOV = 21;
  public static final int INVERSE = 14;
  public static final int ENCRYPT = 17;
  public static final int MATRIX = 12;
  public static final int IDENTIFIER = 22;
  public static final int SEMI_COLON = 11;
  public static final int COLON = 27;
  public static final int LBRACKET = 2;
  public static final int DETERMINANT = 15;
  public static final int RBRACKET = 3;
  public static final int STRING = 25;
  public static final int COMMA = 10;
  public static final int NUMBER = 23;
  public static final int EOF = 0;
  public static final int VECTOR = 26;
  public static final int DIVIDE = 9;
  public static final int LPARENTHESIS = 4;
  public static final int RPARENTHESIS = 5;
  public static final int MINUS = 8;
  public static final int error = 1;
  public static final int ARITH = 13;
  public static final int JORDAN = 20;
  public static final int UNKNOWN = 24;
  public static final int GAUSS = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACKET",
  "RBRACKET",
  "LPARENTHESIS",
  "RPARENTHESIS",
  "PLUS",
  "TIMES",
  "MINUS",
  "DIVIDE",
  "COMMA",
  "SEMI_COLON",
  "MATRIX",
  "ARITH",
  "INVERSE",
  "DETERMINANT",
  "RANK",
  "ENCRYPT",
  "DECRYPT",
  "GAUSS",
  "JORDAN",
  "MARKOV",
  "IDENTIFIER",
  "NUMBER",
  "UNKNOWN",
  "STRING",
  "VECTOR",
  "COLON"
  };
}

