
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'GAUSS GAUSS_JORDAN ID MATRIX NEWLINE NUMBERcode_file : matrix_section solve_sectionmatrix_section   : matrix_declaration\n                        | matrix_declaration matrix_sectionmatrix_declaration : MATRIX ID NEWLINE matrix_content matrix_content   : matrix_row NEWLINE\n                        | matrix_row NEWLINE matrix_contentmatrix_row   : NUMBER\n                    | NUMBER matrix_rowsolve_section : gauss_operations\n                     | gauss_operations solve_sectiongauss_operations : gauss_section\n                        | gausss_jordan_sectiongauss_section : GAUSS id_list NEWLINEgausss_jordan_section : GAUSS_JORDAN id_list NEWLINEid_list : ID\n               | ID id_list'
    
_lr_action_items = {'MATRIX':([0,3,21,24,26,],[4,4,-4,-5,-6,]),'$end':([1,5,6,7,8,13,18,20,],[0,-1,-9,-11,-12,-10,-13,-14,]),'GAUSS':([2,3,6,7,8,11,18,20,21,24,26,],[9,-2,9,-11,-12,-3,-13,-14,-4,-5,-6,]),'GAUSS_JORDAN':([2,3,6,7,8,11,18,20,21,24,26,],[10,-2,10,-11,-12,-3,-13,-14,-4,-5,-6,]),'ID':([4,9,10,15,],[12,15,15,15,]),'NEWLINE':([12,14,15,16,19,22,23,25,],[17,18,-15,20,-16,24,-7,-8,]),'NUMBER':([17,23,24,],[23,23,23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'code_file':([0,],[1,]),'matrix_section':([0,3,],[2,11,]),'matrix_declaration':([0,3,],[3,3,]),'solve_section':([2,6,],[5,13,]),'gauss_operations':([2,6,],[6,6,]),'gauss_section':([2,6,],[7,7,]),'gausss_jordan_section':([2,6,],[8,8,]),'id_list':([9,10,15,],[14,16,19,]),'matrix_content':([17,24,],[21,26,]),'matrix_row':([17,23,24,],[22,25,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> code_file","S'",1,None,None,None),
  ('code_file -> matrix_section solve_section','code_file',2,'p_code_matrix','MatrixParser.py',11),
  ('matrix_section -> matrix_declaration','matrix_section',1,'p_matrix_dec_section','MatrixParser.py',19),
  ('matrix_section -> matrix_declaration matrix_section','matrix_section',2,'p_matrix_dec_section','MatrixParser.py',20),
  ('matrix_declaration -> MATRIX ID NEWLINE matrix_content','matrix_declaration',4,'p_matrix_declaration','MatrixParser.py',28),
  ('matrix_content -> matrix_row NEWLINE','matrix_content',2,'p_matrix_definition','MatrixParser.py',32),
  ('matrix_content -> matrix_row NEWLINE matrix_content','matrix_content',3,'p_matrix_definition','MatrixParser.py',33),
  ('matrix_row -> NUMBER','matrix_row',1,'p_matrix_definition_line','MatrixParser.py',41),
  ('matrix_row -> NUMBER matrix_row','matrix_row',2,'p_matrix_definition_line','MatrixParser.py',42),
  ('solve_section -> gauss_operations','solve_section',1,'p_solve_section','MatrixParser.py',51),
  ('solve_section -> gauss_operations solve_section','solve_section',2,'p_solve_section','MatrixParser.py',52),
  ('gauss_operations -> gauss_section','gauss_operations',1,'p_gauss_operations','MatrixParser.py',60),
  ('gauss_operations -> gausss_jordan_section','gauss_operations',1,'p_gauss_operations','MatrixParser.py',61),
  ('gauss_section -> GAUSS id_list NEWLINE','gauss_section',3,'p_gauss_section','MatrixParser.py',65),
  ('gausss_jordan_section -> GAUSS_JORDAN id_list NEWLINE','gausss_jordan_section',3,'p_gauss_jordan_section','MatrixParser.py',69),
  ('id_list -> ID','id_list',1,'p_id_list','MatrixParser.py',74),
  ('id_list -> ID id_list','id_list',2,'p_id_list','MatrixParser.py',75),
]
